# Clé unique pour le projet
sonar.projectKey=cesizen
sonar.projectName=Cesizen

# Version du projet
sonar.projectVersion=1.0

# Chemin vers le code source
sonar.sources=app,resources/js
sonar.tests=tests

# Encodage des fichiers
sonar.sourceEncoding=UTF-8

# Exclusions : Fichiers et dossiers à ne pas analyser
sonar.exclusions=vendor/**,node_modules/**,public/**,bootstrap/**,storage/**,**/*.blade.php


